### ISSUE TITLE
VSIX file

### ISSUE THREAD

**Issue by trystanmortimer** [mrworkman/papercolor-vscode-redux#3]
Hey mate, the theme is looking great. Might be a silly question, just wondering if you could include the VSIX file in the repo or point me in the direction of how to build it.

**Comment by mrworkman** [comment]
Sorry for the delay, I wasn't notified about this for some reason.

The vsix file(s) can be downloaded from the marketplace if you need it: https://marketplace.visualstudio.com/items?itemName=mrworkman.papercolor-vscode-redux (see the **Version History** tab).

You can build the vsix file yourself using `vsce package`, but you'll need to install nodejs. See here for more info: https://code.visualstudio.com/api/working-with-extensions/publishing-extension.

**Comment by mrworkman** [comment]
I realised you'll need more to go on than just that if you want to build a vsix. The project uses a YAML file which first needs to be converted to JSON in order to build a useful extension.

You can do that using npm.

```shell
$ npm run build
```

Or, to build _and_ package:

```shell
$ npm run package
```
